title: Stephanie Danquah
logo: https://media.licdn.com/dms/image/v2/D4E03AQEdpOrs7In4hQ/profile-displayphoto-crop_800_800/B4EZlg6zYrKYAI-/0/1758267652053?e=1765411200&v=beta&t=2LJymeNmVKR6CJ4fQuVJdZAz6L0bGAEvcSgcZZGbzEI
theme: jekyll-theme-minimal
